### ISSUE TITLE
Error message after installation: Call to a member function count() on null

### ISSUE THREAD

**Issue by q2apro** [kongondo/Blog#28]
Installed the module, afterwards clicking on "Posts" gives: 

```
Error: Uncaught Error: Call to a member function count() on null in C:\uniserver\www\processwire\site\assets\cache\FileCompiler\site\modules\MarkupBlog\ProcessBlog.module:1355
Stack trace:
#0 [internal function]: ProcessBlog->___executePosts()
#1 C:\uniserver\www\processwire\wire\core\Wire.php(347): call_user_func_array(Array, Array)
#2 C:\uniserver\www\processwire\wire\core\WireHooks.php(548): ProcessWire\Wire->_callMethod('___executePosts', Array)
#3 C:\uniserver\www\processwire\wire\core\Wire.php(370): ProcessWire\WireHooks->runHooks(Object(ProcessBlog), 'executePosts', Array)
#4 C:\uniserver\www\processwire\wire\core\ProcessController.php(240): ProcessWire\Wire->__call('executePosts', Array)
#5 [internal function]: ProcessWire\ProcessController->___execute()
#6 C:\uniserver\www\processwire\wire\core\Wire.php(347): call_user_func_array(Array, Array)
#7 C:\uniserver\www\processwire\wire\core\WireHooks.php(548): ProcessWire\Wire->_callMethod('___execute', Array)
#8 C:\uniserver\www\processwire\wire\core\Wire.php(37 (line 1355 of C:\uniserver\www\processwire\site\assets\cache\FileCompiler\site\modules\MarkupBlog\ProcessBlog.module) 

This error message was shown because: you are logged in as a Superuser. Error has been logged.
```

**Comment by Horjan** [comment]
The error message comes if you install the ProcessBlog on processwire-version > 2.7

**Comment by kongondo** [comment]
Hi @Horjan. Please check out the latest version as per this commit(ba1412f2ff36a11fee191fae046ccee43259e4fc). Blog is now compatible with ProcessWire version > 2.7. Thanks.
